# decision_engine.py

from __future__ import annotations
import sys
import os
from pathlib import Path
import json
import logging
from typing import Dict, Any, Optional, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from config import settings
from payments.x402_client import X402PaymentClient
from utils.file_manager import append_agent_log

logger = logging.getLogger("EveronAgent")


class EveronDecisionEngine:
    """
    Production-grade multi-service intelligence synthesis engine for Everon.
    Routes technical analysis matrices to Gemini and coordinates structural JSON
    generation via GPT-4o using Ace Data Cloud's infrastructure. Handles mathematical
    indecision state exceptions with explicit telemetric warnings and advice.
    """

    def __init__(self, x402_client: Optional[X402PaymentClient] = None) -> None:
        self.agent_name = "Everon"
        # Inject or initialize the dedicated payment helper
        self.x402_client = x402_client or X402PaymentClient()
        
        # Define explicit target backend URLs under the Ace Track
        self.gemini_url = "https://api.acedata.cloud/gemini/chat/completions"
        self.gpt_url = "https://api.acedata.cloud/openai/chat/completions"

    def calculate_sentiment_bias(self, sentiment_results: List[Dict[str, Any]]) -> float:
        """
        Processes an array of news items analyzed by hybrid_sentiment to produce 
        a normalized directional vector between -1.0 (bearish) and +1.0 (bullish).
        """
        if not sentiment_results:
            return 0.0
            
        total_score = 0.0
        count = 0
        for item in sentiment_results:
            score = item.get("sentiment_score", 0.0)
            # Factor in confidence level as a variable scalar weighting matrix
            confidence = item.get("confidence", 1.0)
            total_score += (score * confidence)
            count += 1
            
        return total_score / count if count > 0 else 0.0

    def calculate_technical_bias(self, tech_summary: Dict[str, Any]) -> float:
        """
        Maps local pandas indicators into a standardized numerical scale 
        between -1.0 (strongly oversold/bearish) and +1.0 (strongly overbought/bullish).
        """
        if not tech_summary:
            return 0.0
            
        score = 0.0
        # Check explicit flags generated by technical_analysis.py
        if tech_summary.get("GOLDEN_X"): score += 0.5
        if tech_summary.get("DEATH_X"): score -= 0.5
        
        rsi = tech_summary.get("RSI_14", 50.0)
        if rsi > 70: score -= 0.25  # Overbought bias reversal
        elif rsi < 30: score += 0.25  # Oversold bias reversal
        
        macd = tech_summary.get("MACD_12_26_9", 0.0)
        signal = tech_summary.get("MACDs_12_26_9", 0.0)
        if macd > signal: score += 0.25
        elif macd < signal: score -= 0.25
        
        return max(-1.0, min(1.0, score))

    async def analyze_asset(self, token: str, tech_summary: Dict[str, Any], sentiment_items: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Fuses technical and sentiment indicators. Invokes Gemini for linguistic synthesis
        and GPT-4o for final structural execution vectors. Handles tie-breaking anomalies.
        
        Args:
            token: The ticker symbol of the target asset (e.g., SOL, BTC, HYPE).
            tech_summary: Dictionary of technical indicator states.
            sentiment_items: List of dictionaries tracking recent news sentiment analysis.
            
        Returns:
            Dict[str, Any]: Integrated analytical summary conforming to dashboard requirements.
        """
        await append_agent_log(f"[{self.agent_name}] Evaluating intelligence divergence matrix for asset: {token}")
        
        tech_bias = self.calculate_technical_bias(tech_summary)
        sentiment_bias = self.calculate_sentiment_bias(sentiment_items)
        
        # Check for sharp indecision boundary limits (Opposing trends crossing thresholds)
        is_indecisive = False
        reasons = []
        advice = "Maintain normal systematic rebalancing allocations."

        # Case 1: Metrics directly oppose and cancel each other out
        if abs(tech_bias) > 0.2 and abs(sentiment_bias) > 0.2 and (tech_bias * sentiment_bias) < 0:
            is_indecisive = True
            reasons.append(f"Sharp structural decoupling detected: Technical index points to {tech_bias:.2f}, while social sentiment registers {sentiment_bias:.2f}.")
            advice = "Execute capital insulation protocols. Halve positional execution leverage and wait for momentum convergence."
            
        # Case 2: Complete volatility compression (lack of signal)
        if abs(tech_bias) < 0.15 and abs(sentiment_bias) < 0.15:
            is_indecisive = True
            reasons.append(f"Volatility compression exception: Low interaction profile across technical and social metrics (Tech: {tech_bias:.2f}, Sentiment: {sentiment_bias:.2f}).")
            advice = "Sideways consolidation alert. Keep asset allocation bounded within strict market-neutral option ranges."

        # Step 1: Synthesize a qualitative narrative outlook strictly through Gemini-Pro
        gemini_summary = await self._query_gemini_summary(token, tech_summary, sentiment_bias)
        
        # Step 2: Formulate the final structural framing data output strictly through GPT-4o
        final_intelligence = await self._query_gpt_structure(token, gemini_summary, tech_bias, sentiment_bias)
        
        # Step 3: Inject operational warnings if the engine resolves an active state of indecision
        if is_indecisive:
            await append_agent_log(f"[{self.agent_name}] ⚠️ INDECISION LAYER TRIGGERED FOR {token}: Technical and social forces are divergent.", level="WARNING")
            final_intelligence["decision_status"] = "INDECISIVE"
            final_intelligence["indecision_telemetry"] = {
                "warning": f"Everon identified highly ambiguous validation matrices for {token}.",
                "reasons": reasons,
                "strategic_advice": advice
            }
        else:
            final_intelligence["decision_status"] = "CONVERGENT"
            final_intelligence["indecision_telemetry"] = None

        return final_intelligence

    async def _query_gemini_summary(self, token: str, tech_summary: Dict[str, Any], sentiment_bias: float) -> str:
        """
        Routes technical and trend telemetry strictly to the Gemini API cluster
        to output a narrative market intelligence synthesis.
        """
        sdk_client = await self.x402_client.get_managed_sdk_client()
        if not sdk_client:
            return "Fallback: Gemini service connection omitted due to missing payment configuration parameters."

        prompt = (
            f"You are the linguistic core for Everon. Synthesize a concise market trend summary for {token}.\n"
            f"Technical Metrics Array: {tech_summary}\n"
            f"Computed Social Sentiment Vector Scale (-1 to 1): {sentiment_bias}\n"
            f"Identify primary resistance thresholds and clear macroeconomic signals. Keep output under 3 sentences."
        )

        try:
            # Explicit call target mapping directly to the Gemini Pro completions payload framework
            response = await sdk_client.post(
                self.gemini_url,
                json={
                    "model": "gemini-pro",
                    "messages": [{"role": "user", "content": prompt}]
                }
            )
            
            if response.status_code == 200:
                result_json = response.json()
                return result_json.get("choices", [{}])[0].get("message", {}).get("content", "Trend synthesis unavailable.")
            
            logger.error(f"Gemini cluster query returned unexpected status boundary [{response.status_code}]")
            return "Market trend synthesis currently offline."
            
        except Exception as e:
            logger.error(f"Failed query translation to Gemini: {e}")
            return "Trend aggregation sequence error."

    async def _query_gpt_structure(self, token: str, gemini_summary: str, tech_bias: float, sentiment_bias: float) -> Dict[str, Any]:
        """
        Routes structural context to GPT-4o to build a strict, raw JSON output block
        tracking directional vectors and statistical confidence indices.
        """
        sdk_client = await self.x402_client.get_managed_sdk_client()
        default_payload = {
            "token": token,
            "confidence_score": 0.50,
            "directional_bias": "NEUTRAL",
            "gemini_narrative": gemini_summary
        }

        if not sdk_client:
            return default_payload

        prompt = (
            f"Output a strict JSON object mapping the market parameters for {token}.\n"
            f"Gemini Qualitative Narrative: {gemini_summary}\n"
            f"Calculated Inputs -> Technical Weight: {tech_bias}, Sentiment Weight: {sentiment_bias}\n"
            f"Your output must conform strictly to this JSON format without markdown wraps or backticks:\n"
            f'{{"token": "{token}", "confidence_score": 0.00, "directional_bias": "BULLISH/BEARISH/NEUTRAL"}}'
        )

        try:
            # Explicit call target mapping directly to the OpenAI GPT-4o model structure schema
            response = await sdk_client.post(
                self.gpt_url,
                json={
                    "model": "gpt-4o",
                    "messages": [{"role": "user", "content": prompt}]
                }
            )
            
            if response.status_code == 200:
                result_json = response.json()
                content = result_json.get("choices", [{}])[0].get("message", {}).get("content", "")
                
                # Sanitize the output to extract raw JSON if markdown code wrappers slip through
                if "```json" in content:
                    content = content.split("```json")[1].split("```")[0].strip()
                elif "```" in content:
                    content = content.split("
```")[1].split("```")[0].strip()
                    
                parsed_structure = json.loads(content.strip())
                parsed_structure["gemini_narrative"] = gemini_summary
                return parsed_structure
                
            return default_payload

        except Exception as e:
            logger.error(f"Failed to generate structured JSON vector from GPT cluster: {e}")
            return default_payload